#!/bin/sh

#
# Copyright 2022-2023 The Squall Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

script=$0
while [ -h "$script" ]; do
  script=$(readlink -f "$script")
done
script_dir=$(dirname "$script")

[ -z "$SQUALL_HOME" ] && SQUALL_HOME=$(cd "$script_dir/.." > /dev/null; pwd)

if [ -z "$JAVA_HOME" ]
then
    java_cmd=$(which java)
else
    java_cmd="$JAVA_HOME/bin/java"
fi

module=dev.openclosed.squall.cli
exec "$java_cmd" -p "$SQUALL_HOME/lib" -m $module "$@"
